### PR TITLE
Build using swig source, continuous integration with Travis CI

### PR DESCRIPTION
**Pull request by klauer**
This builds on @zackw 's [fork](https://github.com/zackw/mecab-python3) - which removes the pre-wrapped C++ source and pre-built object files (and adds Debian packaging metadata).

It also:
 * Adds a simple travis configuration for CI ([result](https://travis-ci.org/klauer/mecab-python3/jobs/239157315))
 * Reverts some README/setup.py changes for merging here
 * Adds back the VERSION variable for compatibility purposes

### CODE REVIEW

**Comment by SamuraiT** [comment]
@klauer thank you for adding so many features. I didn't recognize until this very moment...
Looks good to me. so let me just merge it 💃

**Comment by SamuraiT** [comment]
Also you wrote clean and very nice code. 
Let me offer you to be maintainer/committer for mecab-python3. 
so I'll add you as a collaborator for this repo.

**Comment by SamuraiT** [comment]
if you don't mind, let me add you @zackw as a maintainer/committer for mecab-python3. 👍

**Comment by zackw** [comment]
Thank you! I don't have any further plans for mecab-python3 myself but I am happy to help out as needed.

**Pull request merged**
