### PR TITLE
Make node.surface return just the token (fixes #19)

### LINKED ISSUE #19: node.surface() does not work as intended in version 0.996.1
My Environment:
OS: Tried on both Ubuntu 16.04 and Windows 10 
Python: 3.6.3
mecab-python3: 0.996.1

Hi,

I recently found that node.surface is not working as intended in version 0.996.1. 

```
#coding:utf-8

import MeCab

# MeCabのインスタンス作成
mecab = MeCab.Tagger('-Ochasen')
mecab.parseToNode('')       # MeCab上の不具合で一度空で解析すると解消される

# 一行毎に解析開始
text = 'これはテストです。Mecabバージョン0.996.1'
node = mecab.parseToNode(text)

# 一単語毎に解析
while node:
    word_surface = node.surface
    print(word_surface)
    node = node.next
```

This produces the following result: 
image

However, on previous versions:
image

Thanks!

### PR DESCRIPTION
**Pull request by polm**
For details on the fix see #19, particularly comments by @tomoyukih-fw.

### CODE REVIEW

**Comment by polm** [comment]
Thank you very much for your quick reply.

Good point about leaking memory, but my understanding is that making sure the new string gets cleaned up is the purpose of the [`newobject` directive](http://www.swig.org/Doc1.3/Customization.html#ownership):

> If you wrap the function blah(), SWIG has no idea that the return value is a newly allocated object. As a result, the resulting extension module may produce a memory leak (SWIG is conservative and will never delete objects unless it knows for certain that the returned object was newly created).
> ...
> When %newobject is supplied, many language modules will arrange to take ownership of the return value. This allows the value to be automatically garbage-collected when it is no longer in use. However, this depends entirely on the target language (a language module may also choose to ignore the %newobject directive).

So I think this is OK. I can write a test or check more closely if you like though.

No worries about looking at it this weekend or later; since the old version works this isn't urgent for me by any means. Thanks again for your quick reply.

**Comment by zackw** [comment]
If you can somehow confirm that `%newobject` does cause the intermediate C-string to be deallocated, that would satisfy me for now.  I would _like_ to ask for a test program but we don't actually have a test suite right now (which is a problem in itself, but not one we need to address at the same time as this regression).

**Comment by polm** [comment]
Would showing a loop with the same operation has constant memory usage be adequate? This seems to work:

```
import MeCab
tokenizer = MeCab.Tagger()

import os
import psutil # note: needs to be installed
process = psutil.Process(os.getpid())

for ii in range(100000):
    node = tokenizer.parseToNode('日本語ですよ').next
    a = node.surface

    if (ii + 1) % 10000 == 0:
        # This should print memory usage 
        print(process.memory_info().rss)
        # if there is no memory leak the number should not change

```

I need to go to bed now, but if this isn't adequate I could look into hunting down the implementation of `newobject` in swig - otherwise not really sure how to prove the pointer is deallocated.

**Comment by zackw** [comment]
That will do; I can run that program under `valgrind` or something for an even more stringent test.  Thanks.  Again, not going to actually merge the PR until I have time to dig into the changes a bit more myself, but I think we're on the right track.

**Comment by zackw** [comment]
I have now thoroughly verified that this code does not produce a memory leak.  Also, on further investigation, this code (with trivial formatting changes) _is_ in the latest version of the upstream `MeCab.i`, so clearly it is the intended API.

I've merged your PR and then committed a patch on top of it to make the formatting match the upstream file.  There will be a new release on PyPI Real Soon Now (I need to sort out automatic building of binary wheels, first).

**Pull request merged**
